name: Test

on: [push]

jobs:
    test:
        name: GithubTest
        runs-on: macOS-latest
        strategy:
            matrix:
                xcode: [11.2_beta 2]
                destination: ['platform=iOS Simulator,OS=13.2.2, name=iPhone 11']

        steps:
            - uses: YOCKOW/Action-setup-swift@master
              with:
                swift-version: '5.1.2' # This value is passed to swiftenv without modification.
                swift-package-directory: "./my-swift-package"
            - run: swift --version
            - name: Checkout
              uses: actions/checkout@master
            - name: Github Action test
              id: test_app
              run: |
                 xcodebuild clean build \
                 -workspace NotiCheck.xcodeproj \
                 -scheme NotiCheck\ iOS \
                 -destination "${destination}" \
                 -configuration Debug \
                 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO test | xcpretty -c; echo "::set-output name=result::${PIPESTATUS[0]}"; echo "${PIPESTATUS[0]}"
              env:
                destination: ${{ matrix.destination }}
#        - name: iOS test
#          id: ios_test
#          run: |
#                 xcodebuild clean build \
#                 -workspace BizTalk.xcworkspace \
#                 -scheme Repository \
#                 -destination "${destination}" \
#                 -configuration Debug \
#                 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO test | xcpretty -c; echo "::set-output name=result::${PIPESTATUS[0]}"; echo "${PIPESTATUS[0]}"
#          env: destination: ${{ matrix.destination }}
#  build:
#
#    runs-on: macOS-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v
